### ISSUE TITLE
Any plan to update to 0.15 ?

### ISSUE THREAD

**Issue by yang-wei** [grzegorzbalcerek/elm-by-example#7]

**Comment by grzegorzbalcerek** [comment]
I think I will upgrade to a newer Elm version than what I used so far, but I am not sure when exactly. I will probably use a different approach though and not update this repository.

**Comment by yang-wei** [comment]
Fair enough. Elm Api changes a lot from 0.14 to 0.15. 
But your examples are great ! Thanks for making this =)
